/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DibujoGrafo;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author escar
 */
public class bolitasypalitos extends javax.swing.JFrame {

    /**
     * Creates new form bolitasypalitos
     */
    public bolitasypalitos() {
      
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        flecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        s0 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        s1 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        s3 = new javax.swing.JTextField();
        a4 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        armado = new javax.swing.JButton();
        s4 = new javax.swing.JTextField();
        a5 = new javax.swing.JTextField();
        b5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        s5 = new javax.swing.JTextField();
        a6 = new javax.swing.JTextField();
        b6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(0, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));

        flecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatas/imagen/t.png"))); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(flecha)
                .addContainerGap(485, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(flecha)
                .addContainerGap(364, Short.MAX_VALUE))
        );

        jLabel1.setText("ESTADO");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setText("a");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel3.setText("b");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });

        armado.setText("armado");
        armado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));
        armado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                armadoActionPerformed(evt);
            }
        });

        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });

        jButton1.setText("Borrar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.darkGray));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(s0)
                                    .addComponent(s1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s3))
                                .addGap(14, 14, 14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(jLabel2)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(31, 31, 31)
                                            .addComponent(jLabel3))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(b1))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(a5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(a4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(a6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(armado)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(s0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113)
                        .addComponent(armado)
                        .addGap(46, 46, 46)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s3ActionPerformed

    private void armadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armadoActionPerformed
       
       Graphics g = panel.getGraphics();
     //-----------------------------------------------------------------ESTADO S0  
     if(s0.getText().equals("s0")){
         flecha.setVisible(true);
            g.drawOval(100,100,50,50);   
            g.drawString("S0", 120,130);
           
           }
     else if(s0.getText().equals("s0a")){
            g.drawOval(100,100,50,50);
            g.drawOval(105,105,40,40);
            g.drawString("S0", 120,130);
            flecha.setVisible(true);
           }
     //------------------------------------A´S DE S0
     if (a1.getText().equals("s0")){
         g.setColor(Color.blue);
         g.drawLine(105,105,105,80);
         g.drawLine(105,80,120,80);
         g.drawLine(120,80,120,100);
         g.drawLine(120,100,110,90);
         g.drawString("A",95,95);
         
         
     }
     else if(a1.getText().equals("s1")){
         g.setColor(Color.blue);
         g.drawLine(120,100,255,110);
         g.drawLine(255,110,245,95);
         g.drawString("A",200,103);
         
     }
     else if(a1.getText().equals("s2")){
         g.setColor(Color.blue);
         g.drawLine(140,145,265,200);
         g.drawLine(265,200,255,185);
         g.drawString("A",200,170);
     }
     else if (a1.getText().equals("s3")){
         g.setColor(Color.blue);
         g.drawLine(100,130,110,210);
         g.drawLine(110,210,100,200);
         g.drawString("A",95,200);
     }
     else if(a1.getText().equals("s4")){
         g.setColor(Color.blue);
         g.drawLine(100,130,25,150);
         g.drawLine(25,150,190,350);
         g.drawLine(190,350,175,340);
         g.drawString("A",22,150);
     }
     else if (a1.getText().equals("s5")){
         g.setColor(Color.blue);
         g.drawLine(120,100,120,80);
         g.drawLine(120,80,420,80);
         g.drawLine(420,80,420,150);
         g.drawLine(420,150,430,140);
         g.drawString("A", 440, 145);
     }
     //---------------------------------------B´S DE S0
     if (b1.getText().equals("s0")){
          g.setColor(Color.blue);
         g.drawLine(105,105,105,80);
         g.drawLine(105,80,120,80);
         g.drawLine(120,80,120,100);
         g.drawLine(120,100,110,90);
         g.drawString("B",80,95);
         
         
     }
     else if(b1.getText().equals("s1")){
         g.setColor(Color.blue);
           g.drawLine(120,100,255,110);
         g.drawLine(255,110,245,95);
         g.drawString("B",210,103);
         
     }
     else if(b1.getText().equals("s2")){
         g.setColor(Color.blue);
         g.drawLine(140,145,265,200);
         g.drawLine(265,200,255,185);
         g.drawString("B",190,170);
     }
     else if (b1.getText().equals("s3")){
         g.setColor(Color.blue);
        g.drawLine(100,130,110,210);
         g.drawLine(110,210,100,200);
         g.drawString("B",105,200);
     }
     else if(b1.getText().equals("s4")){
         g.setColor(Color.blue);
         g.drawLine(100,130,25,150);
         g.drawLine(25,150,190,350);
         g.drawLine(190,350,175,340);
         g.drawString("B",12,150);
     }
     
      else if (b1.getText().equals("s5")){
         g.setColor(Color.blue);
         g.drawLine(120,100,120,80);
         g.drawLine(120,80,420,80);
         g.drawLine(420,80,420,150);
         g.drawLine(420,150,430,140);
         g.drawString("B", 430, 145);
      }
     
        //---------------------------------------------------------------ESTADO S1
       if(s1.getText().equals("s1")){
            g.setColor(Color.black);
            g.drawOval(250,100,50,50);
            g.drawString("S1",265,127 );
        }
       else if(s1.getText().equals("s1a")){
           g.setColor(Color.black);
            g.drawOval(250,100,50,50);
            g.drawOval(255,105,40,40);
             g.drawString("S1",265,127 );
           }
       
       //-------------------------------------A´S DE S1
     if (a2.getText().equals("s0")){
          g.setColor(Color.DARK_GRAY);
         g.drawLine(150,130,280,150);
         g.drawLine(150,130,160,140);
         g.drawString("A",165,144);
      }
     else if(a2.getText().equals("s1")){
         g.setColor(Color.DARK_GRAY);
         g.drawLine(260,107,260,75);
         g.drawLine(260,75,285,75);
         g.drawLine(285,75,285,105);
         g.drawLine(285,105,295,95);
         g.drawString("A",250,100);
         
     }
    else if(a2.getText().equals("s2")){
         g.setColor(Color.DARK_GRAY);
          g.drawLine(250,120,260,200);
         g.drawLine(260,200,270,190);
         g.drawString("A",240,170);
     }
     else if (a2.getText().equals("s3")){
         g.setColor(Color.DARK_GRAY);
         g.drawLine(150,210,252,120);
         g.drawLine(150,210,160,195);
         g.drawString("A",170,200);
     }
     
     
     else if(a2.getText().equals("s4")){
         g.setColor(Color.DARK_GRAY);
         g.drawLine(300,135,350,360);
         g.drawLine(350,360,225,360);
         g.drawLine(225,360,230,350);
         g.drawString("A",235,360);
     }
     else if(a2.getText().equals("s5")){
         g.setColor(Color.DARK_GRAY);
         g.drawLine(300,110,350,90);
         g.drawLine(350,90,410,150);
         g.drawLine(410,150,415,145);
         g.drawString("A",360,120);
     }
       
       
     //---------------------------------------B´S DE S1
     
     if (b2.getText().equals("s0")){
         g.setColor(Color.DARK_GRAY);
         g.drawLine(150,130,280,150);
         g.drawLine(150,130,160,140);
         g.drawString("B",175,144);
      }
     else if(b2.getText().equals("s1")){
         g.setColor(Color.DARK_GRAY);
         g.drawLine(260,107,260,75);
         g.drawLine(260,75,285,75);
         g.drawLine(285,75,285,105);
         g.drawLine(285,105,295,95);
         g.drawString("B",240,100);
         
     }
    else if(b2.getText().equals("s2")){
         g.setColor(Color.DARK_GRAY);
          g.drawLine(250,120,260,200);
         g.drawLine(260,200,270,190);
         g.drawString("B",230,170);
     }
     else if (b2.getText().equals("s3")){
         g.setColor(Color.DARK_GRAY);
         g.drawLine(150,210,252,120);
         g.drawLine(150,210,160,195);
         g.drawString("B",160,190);
     }
     else if(b2.getText().equals("s4")){
         g.setColor(Color.DARK_GRAY);
         g.drawLine(300,135,350,360);
         g.drawLine(350,360,225,360);
         g.drawLine(225,360,230,350);
         g.drawString("B",245,360);
     }
       
        else if(b2.getText().equals("s5")){
         g.setColor(Color.DARK_GRAY);
         g.drawLine(300,110,350,90);
         g.drawLine(350,90,410,150);
         g.drawLine(410,150,415,145);
         g.drawString("B",370,120);
     }
       
       
       
       //-----------------------------------------------------------ESTADO S2
        if(s2.getText().equals("s2") ){
            g.setColor(Color.black);
            g.drawOval(250,200,50,50);
            g.drawString("S2",265,227);
        }
        else if(s2.getText().equals("s2a")){
            g.setColor(Color.black);
            
            g.drawOval(250,200,50,50);
            g.drawOval(255,205,40,40);
            g.drawString("S2",265,227);
           }
        
        //-----------------------------------A´S DE S2     
         if (a3.getText().equals("s0")){
          g.setColor(Color.RED);
         g.drawLine( 260,205,125,175);
         g.drawLine(125,175,135,150);
         g.drawLine(135,150,140,160);
         g.drawString("A",136,175);
      }
      else if(a3.getText().equals("s1")){
         g.setColor(Color.RED);
         g.drawLine(300,225,290,145);
         g.drawLine(290,145,305,150);
         g.drawString("A",300,160);
         
     }
    else if(a3.getText().equals("s2")){
         g.setColor(Color.RED);
          g.drawLine(300,235,320,235);
         g.drawLine(320,235,320,215);
         g.drawLine(320,215,300,215);
         g.drawLine(300,215,310,203);
         g.drawString("A",325,236);
     }
    else if (a3.getText().equals("s3")){
         g.setColor(Color.RED);
         g.drawLine(150,220,250,220);
         g.drawLine(150,220,160,230);
        g.drawString("A",180,230);
     }
     
   else if(a3.getText().equals("s4")){
         g.setColor(Color.RED);
         g.drawLine(298,240,215,360);
         g.drawLine(215,360,220,340);
        g.drawString("A",298,260);
     }
          else if(a3.getText().equals("s5")){
         g.setColor(Color.RED);
         g.drawLine(300,215,400,165);
         g.drawLine(400,165,390,155);
        g.drawString("A",370,190);
     }
       
    //-----------------------------------B´S DE S2    
       if (b3.getText().equals("s0")){
          g.setColor(Color.RED);
         g.drawLine( 260,205,125,175);
         g.drawLine(125,175,135,150);
         g.drawLine(135,150,140,160);
         g.drawString("B",146,175);
      }
      else if(b3.getText().equals("s1")){
         g.setColor(Color.RED);
         g.drawLine(300,225,290,145);
         g.drawLine(290,145,305,150);
         g.drawString("B",310,160);
         
     }
    else if(b3.getText().equals("s2")){
         g.setColor(Color.RED);
          g.drawLine(300,235,320,235);
         g.drawLine(320,235,320,215);
         g.drawLine(320,215,300,215);
         g.drawLine(300,215,310,203);
         g.drawString("B",335,236);
     }
    else if (b3.getText().equals("s3")){
         g.setColor(Color.RED);
         g.drawLine(150,220,250,220);
         g.drawLine(150,220,160,230);
        g.drawString("B",190,230);
     }
     
   else if(b3.getText().equals("s4")){
         g.setColor(Color.RED);
         g.drawLine(298,240,215,360);
         g.drawLine(215,360,220,340);
        g.drawString("B",308,260);
     }
        
            else if(b3.getText().equals("s5")){
         g.setColor(Color.RED);
         g.drawLine(300,215,400,165);
         g.drawLine(400,165,390,155);
        g.drawString("B",380,190);
     }
       
        
  //-------------------------------------------------------------ESTADO S3 
        if(s3.getText().equals("s3")){
            g.setColor(Color.black);
            g.drawOval(100,200,50,50);
            g.drawString("S3",120,230);
        }
        else if(s3.getText().equals("s3a")){
            g.setColor(Color.black);
            g.drawOval(100,200,50,50);
            g.drawOval(105,205,40,40);
            g.drawString("S3",120,230);
           }
        //-------------------- A´S DE S3
        
        if (a4.getText().equals("s0")){
          g.setColor(Color.PINK);
         g.drawLine(120,200,120,150);
         g.drawLine(120,150,110,160);
         g.drawString("A",110,168);
      }
      else if(a4.getText().equals("s1")){
         g.setColor(Color.PINK);
         g.drawLine(153,215,270,145);
         g.drawLine(270,145,265,160);
         g.drawString("A",265,175);
         
     }
      else if(a4.getText().equals("s2")){
         g.setColor(Color.PINK);
         g.drawLine(125,250,250,240);
         g.drawLine(250,240,245,250);
         g.drawString("A",230,255);
     }
    else if (a4.getText().equals("s3")){
         g.setColor(Color.PINK);
         g.drawLine(100,230,80,230);
         g.drawLine(80,230,80,250);
         g.drawLine(80,250,110,250);
         g.drawLine(110,250,100,245);
        g.drawString("A",95,265);
     }
     else if(a4.getText().equals("s4")){
         g.setColor(Color.PINK);
         g.drawLine(125,250,195,350);
         g.drawLine(195,350,200,340);
        g.drawString("A",190,330);
     }
         else if(a4.getText().equals("s5")){
         g.setColor(Color.PINK);
         g.drawLine(130,200,130,180);
         g.drawLine(130,180,400,175);
         g.drawLine(400,175,390,185);
        g.drawString("A",370,170);
     }
         //-------------------- B´S DE S3
        
        if (b4.getText().equals("s0")){
          g.setColor(Color.PINK);
         g.drawLine(120,200,120,150);
         g.drawLine(120,150,110,160);
         g.drawString("B",120,168);
      }
      else if(b4.getText().equals("s1")){
         g.setColor(Color.PINK);
        g.drawLine(153,215,270,145);
         g.drawLine(270,145,265,160);
         g.drawString("B",255,175);
         
     }
      else if(b4.getText().equals("s2")){
         g.setColor(Color.PINK);
         g.drawLine(125,250,250,240);
         g.drawLine(250,240,245,250);
         g.drawString("B",220,255);
     }
    else if (b4.getText().equals("s3")){
         g.setColor(Color.PINK);
         g.drawLine(100,230,80,230);
         g.drawLine(80,230,80,250);
         g.drawLine(80,250,110,250);
         g.drawLine(110,250,100,245);
        g.drawString("B",105,265);
     }
     else if(b4.getText().equals("s4")){
         g.setColor(Color.PINK);
         g.drawLine(125,250,195,350);
         g.drawLine(195,350,200,340);
        g.drawString("B",200,330);
     }
        
        else if(b4.getText().equals("s5")){
         g.setColor(Color.PINK);
         g.drawLine(130,200,130,180);
         g.drawLine(130,180,400,175);
         g.drawLine(400,175,390,185);
        g.drawString("B",380,170);
        }
 
        
        //------------------------------------------------------------Estado s4
        if(s4.getText().equals("s4")){
            g.setColor(Color.black);
            g.drawOval(175,350,50,50);
            g.drawString("S4", 195,377);
        }
        else if(s4.getText().equals("s4a")){
            g.setColor(Color.black);
            g.drawOval(175,350,50,50);
            g.drawOval(180,355,40,40);
            g.drawString("S4", 195,377);
            
        }
       //------------------------- A´S DE S4   
        if (a5.getText().equals("s0")){
          g.setColor(Color.GREEN);
         g.drawLine(175,360,10,200);
         g.drawLine(10,200,10,110);
         g.drawLine(10,110,100,110);
         g.drawLine(100,110,90,100);
        g.drawString("A",20,100);
      }
       else if(a5.getText().equals("s1")){
         g.setColor(Color.GREEN);
         g.drawLine(205,350,205,175);
         g.drawLine(205,175,250,115);
         g.drawLine(250,115,240,110);
         g.drawString("A",230,125);
         
     }
      else if(a5.getText().equals("s2")){
         g.setColor(Color.GREEN);
         g.drawLine(215,350,215,240);
         g.drawLine(215,240,250,240);
         g.drawLine(250,240,240,250);
         g.drawString("A",220,250);
     }
      else if (a5.getText().equals("s3")){
         g.setColor(Color.GREEN);
         g.drawLine(184,350,115,290);
        g.drawLine(115,290,115,250);
        g.drawLine(115,250,125,260);
       g.drawString("A",120,270);
     }
    else if(a5.getText().equals("s4")){
         g.setColor(Color.GREEN);
         g.drawLine(180,390,180,419);
         g.drawLine(180,419,210,419);
         g.drawLine(210,419,210,400);
         g.drawLine(210,400,200,415);
        g.drawString("A",220,419);
     }
        else if(a5.getText().equals("s5")){
         g.setColor(Color.GREEN);
         g.drawLine(190,400,420,400);
         g.drawLine(420,400,410,200);
         g.drawLine(410,200,400,210);
         g.drawString("A",430,400);
     }
        
        
     //------------------------------------------B´S DE S4
      
        if (b5.getText().equals("s0")){
          g.setColor(Color.GREEN);
         g.drawLine(175,360,10,200);
         g.drawLine(10,200,10,110);
         g.drawLine(10,110,100,110);
         g.drawLine(100,110,90,100);
        g.drawString("B",30,100);
      }
       else if(b5.getText().equals("s1")){
         g.setColor(Color.GREEN);
         g.drawLine(205,350,205,175);
         g.drawLine(205,175,250,115);
         g.drawLine(250,115,240,110);
         g.drawString("B",240,125);
         
     }
      else if(b5.getText().equals("s2")){
         g.setColor(Color.GREEN);
         g.drawLine(215,350,215,240);
         g.drawLine(215,240,250,240);
         g.drawLine(250,240,240,250);
         g.drawString("B",230,250);
     }
      else if (b5.getText().equals("s3")){
         g.setColor(Color.GREEN);
         g.drawLine(184,350,115,290);
        g.drawLine(115,290,115,250);
        g.drawLine(115,250,125,260);
       g.drawString("B",130,270);
     }
    else if(b5.getText().equals("s4")){
         g.setColor(Color.GREEN);
         g.drawLine(180,390,180,419);
         g.drawLine(180,419,210,419);
         g.drawLine(210,419,210,400);
         g.drawLine(210,400,200,415);
        g.drawString("B",230,419);
     }
     
      else if(b5.getText().equals("s5")){
         g.setColor(Color.GREEN);
         g.drawLine(190,400,420,400);
         g.drawLine(420,400,410,200);
         g.drawLine(410,200,400,210);
         g.drawString("B",440,400);
     }
        
      //--------------------------------------------------------------ESTADO S5  
       if(s5.getText().equals("s5")){
            g.setColor(Color.black);
            g.drawOval(400,150,50,50);
            g.drawString("S5", 420,180);
        }
        else if(s5.getText().equals("s5a")){
            g.setColor(Color.black);
            g.drawOval(400,150,50,50);
            g.drawOval(405,155,40,40);
            g.drawString("S5", 420,180);
            
        }
     
      //---------------------------------A´S DE S5   
       if (a6.getText().equals("s0")){
          g.setColor(Color.YELLOW);
         g.drawLine(430,150,430,50);
         g.drawLine(430,50,140,50);
         g.drawLine(140,50,140,100);
         g.drawLine(140,100,150,90);
        g.drawString("A",130,90);
      }
       else if(a6.getText().equals("s1")){
         g.setColor(Color.YELLOW);
         g.drawLine(425,155,291,140);
         g.drawLine(291,140,300,150);
         g.drawString("A",305,160);
         
     }
      else if(a6.getText().equals("s2")){
         g.setColor(Color.YELLOW);
         g.drawLine(425,200,425,220);
         g.drawLine(425,220,300,220);
         g.drawLine(300,220,310,230);
         g.drawString("A",320,230);
     }
      
      else if (a6.getText().equals("s3")){
         g.setColor(Color.YELLOW);
         g.drawLine(430,200,430,260);
        g.drawLine(430,260,160,260);
        g.drawLine(160,260,140,240);
        g.drawLine(140,240,150,265);
       g.drawString("A",170,280);
     }
    else if(a6.getText().equals("s4")){
         g.setColor(Color.YELLOW);
         g.drawLine(450,190,450,375);
         g.drawLine(450,375,225,375);
         g.drawLine(225,375,235,385);
        g.drawString("A",340,395);
     }
    else if (a6.getText().equals("s5")){
        g.setColor(Color.YELLOW);
        g.drawLine(450,160,475,160);
        g.drawLine(475,160,475,180);
        g.drawLine(475,180,450,180);
        g.drawLine(450,180,460,170);
        g.drawString("A",480,160);
        
    }
     
       //-----------------B´S DE S5
        if (b6.getText().equals("s0")){
          g.setColor(Color.YELLOW);
         g.drawLine(430,150,430,50);
         g.drawLine(430,50,140,50);
         g.drawLine(140,50,140,100);
         g.drawLine(140,100,150,90);
        g.drawString("B",140,90);
      }
       else if(b6.getText().equals("s1")){
         g.setColor(Color.YELLOW);
         g.drawLine(425,155,291,140);
         g.drawLine(291,140,300,150);
         g.drawString("B",315,160);
         
     }
      else if(b6.getText().equals("s2")){
         g.setColor(Color.YELLOW);
         g.drawLine(425,200,425,220);
         g.drawLine(425,220,300,220);
         g.drawLine(300,220,310,230);
         g.drawString("B",330,230);
     }
      
      else if (b6.getText().equals("s3")){
         g.setColor(Color.YELLOW);
         g.drawLine(430,200,430,260);
        g.drawLine(430,260,160,260);
        g.drawLine(160,260,140,240);
        g.drawLine(140,240,150,265);
       g.drawString("B",180,280);
     }
    else if(b6.getText().equals("s4")){
         g.setColor(Color.YELLOW);
         g.drawLine(450,190,450,375);
         g.drawLine(450,375,225,375);
         g.drawLine(225,375,235,385);
        g.drawString("B",350,395);
     }
       
          else if (b6.getText().equals("s5")){
        g.setColor(Color.YELLOW);
        g.drawLine(450,160,475,160);
        g.drawLine(475,160,475,180);
        g.drawLine(475,180,450,180);
        g.drawLine(450,180,460,170);
        g.drawString("B",490,160);
        
    }
       
       
       
       
       
       
       
            
    }//GEN-LAST:event_armadoActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       panel.repaint();
       a1.setText("");
       a2.setText("");
       a3.setText("");
       a4.setText("");
       a5.setText("");
       b1.setText("");
       b2.setText("");
       b3.setText("");
       b4.setText("");
       b5.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bolitasypalitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bolitasypalitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bolitasypalitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bolitasypalitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bolitasypalitos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JTextField a6;
    private javax.swing.JButton armado;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JTextField b5;
    private javax.swing.JTextField b6;
    private javax.swing.JLabel flecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField s0;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    private javax.swing.JTextField s5;
    // End of variables declaration//GEN-END:variables
}
