/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DibujoGrafo;

import java.awt.BasicStroke;
import java.awt.Graphics2D;

/**
 *
 * @author Jahir
 */
public class Grafos2 extends javax.swing.JFrame {

    Graphics2D g2;
    public Grafos2() {
        initComponents();
        S0.setVisible(false);S1.setVisible(false);S2.setVisible(false);S3.setVisible(false);S4.setVisible(false);S5.setVisible(false);
        jL3.setVisible(false);jL4.setVisible(false);jL5.setVisible(false);jL6.setVisible(false);jL7.setVisible(false);jL8.setVisible(false);
        jL9.setVisible(false);jL10.setVisible(false);jL11.setVisible(false);jL12.setVisible(false);jL13.setVisible(false);jL14.setVisible(false);
        jL15.setVisible(false);jL16.setVisible(false);jL17.setVisible(false);jL18.setVisible(false);jL19.setVisible(false);jL19.setVisible(false);
        jL20.setVisible(false);jL21.setVisible(false);jL22.setVisible(false);jL23.setVisible(false);jL24.setVisible(false);jL25.setVisible(false);
        jL26.setVisible(false);jL27.setVisible(false);jL28.setVisible(false);jL28.setVisible(false);jL29.setVisible(false);jL30.setVisible(false);
        jL31.setVisible(false);jL32.setVisible(false);jL33.setVisible(false);jL34.setVisible(false);jL35.setVisible(false);jL36.setVisible(false);
        jL37.setVisible(false);jL38.setVisible(false);jL39.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grafico = new javax.swing.JPanel();
        S1 = new javax.swing.JLabel();
        S0 = new javax.swing.JLabel();
        S2 = new javax.swing.JLabel();
        S3 = new javax.swing.JLabel();
        S4 = new javax.swing.JLabel();
        S5 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jL4 = new javax.swing.JLabel();
        jL5 = new javax.swing.JLabel();
        jL6 = new javax.swing.JLabel();
        jL7 = new javax.swing.JLabel();
        jL8 = new javax.swing.JLabel();
        jL9 = new javax.swing.JLabel();
        jL10 = new javax.swing.JLabel();
        jL11 = new javax.swing.JLabel();
        jL12 = new javax.swing.JLabel();
        jL13 = new javax.swing.JLabel();
        jL14 = new javax.swing.JLabel();
        jL15 = new javax.swing.JLabel();
        jL16 = new javax.swing.JLabel();
        jL17 = new javax.swing.JLabel();
        jL18 = new javax.swing.JLabel();
        jL19 = new javax.swing.JLabel();
        jL20 = new javax.swing.JLabel();
        jL21 = new javax.swing.JLabel();
        jL22 = new javax.swing.JLabel();
        jL23 = new javax.swing.JLabel();
        jL24 = new javax.swing.JLabel();
        jL25 = new javax.swing.JLabel();
        jL26 = new javax.swing.JLabel();
        jL27 = new javax.swing.JLabel();
        jL28 = new javax.swing.JLabel();
        jL29 = new javax.swing.JLabel();
        jL30 = new javax.swing.JLabel();
        jL31 = new javax.swing.JLabel();
        jL32 = new javax.swing.JLabel();
        jL33 = new javax.swing.JLabel();
        jL34 = new javax.swing.JLabel();
        jL35 = new javax.swing.JLabel();
        jL36 = new javax.swing.JLabel();
        jL37 = new javax.swing.JLabel();
        jL38 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        std0 = new javax.swing.JTextField();
        jtxt1 = new javax.swing.JTextField();
        std3 = new javax.swing.JTextField();
        jtxt2 = new javax.swing.JTextField();
        std1 = new javax.swing.JTextField();
        jtxt3 = new javax.swing.JTextField();
        jtxt4 = new javax.swing.JTextField();
        std2 = new javax.swing.JTextField();
        jtxt5 = new javax.swing.JTextField();
        jtxt6 = new javax.swing.JTextField();
        jtxt7 = new javax.swing.JTextField();
        jtxt8 = new javax.swing.JTextField();
        std4 = new javax.swing.JTextField();
        jtxt9 = new javax.swing.JTextField();
        jtxt10 = new javax.swing.JTextField();
        std5 = new javax.swing.JTextField();
        jtxt11 = new javax.swing.JTextField();
        jtxt12 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jL1 = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jL39 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Grafico.setBackground(new java.awt.Color(255, 255, 255));
        Grafico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Grafico.setLayout(null);

        S1.setText("S1");
        Grafico.add(S1);
        S1.setBounds(85, 139, 20, 14);

        S0.setText("S0");
        Grafico.add(S0);
        S0.setBounds(198, 74, 20, 14);

        S2.setText("S2");
        Grafico.add(S2);
        S2.setBounds(325, 139, 20, 14);

        S3.setText("S3");
        Grafico.add(S3);
        S3.setBounds(80, 260, 20, 14);

        S4.setText("S4");
        Grafico.add(S4);
        S4.setBounds(320, 260, 20, 14);

        S5.setText("S5");
        Grafico.add(S5);
        S5.setBounds(200, 330, 20, 14);

        jL3.setText("a");
        Grafico.add(jL3);
        jL3.setBounds(200, 0, 29, 20);

        jL4.setText("a");
        Grafico.add(jL4);
        jL4.setBounds(140, 110, 29, 20);

        jL5.setText("a");
        Grafico.add(jL5);
        jL5.setBounds(300, 100, 29, 20);

        jL6.setText("a");
        Grafico.add(jL6);
        jL6.setBounds(280, 150, 29, 20);

        jL7.setText("a");
        Grafico.add(jL7);
        jL7.setBounds(120, 220, 29, 20);

        jL8.setText("a");
        Grafico.add(jL8);
        jL8.setBounds(220, 270, 29, 20);

        jL9.setText("a");
        Grafico.add(jL9);
        jL9.setBounds(120, 90, 29, 20);

        jL10.setText("a");
        Grafico.add(jL10);
        jL10.setBounds(30, 120, 29, 20);

        jL11.setText("a");
        Grafico.add(jL11);
        jL11.setBounds(250, 120, 29, 20);

        jL12.setText("a");
        Grafico.add(jL12);
        jL12.setBounds(110, 190, 29, 20);

        jL13.setText("a");
        Grafico.add(jL13);
        jL13.setBounds(220, 190, 29, 20);

        jL14.setText("a");
        Grafico.add(jL14);
        jL14.setBounds(180, 250, 29, 20);

        jL15.setText("a");
        Grafico.add(jL15);
        jL15.setBounds(240, 110, 29, 20);

        jL16.setText("a");
        Grafico.add(jL16);
        jL16.setBounds(160, 160, 29, 20);

        jL17.setText("a");
        Grafico.add(jL17);
        jL17.setBounds(370, 160, 29, 20);

        jL18.setText("a");
        Grafico.add(jL18);
        jL18.setBounds(160, 230, 29, 20);

        jL19.setText("a");
        Grafico.add(jL19);
        jL19.setBounds(350, 200, 29, 20);

        jL20.setText("a");
        Grafico.add(jL20);
        jL20.setBounds(280, 220, 29, 20);

        jL21.setText("a");
        Grafico.add(jL21);
        jL21.setBounds(190, 140, 29, 20);

        jL22.setText("a");
        Grafico.add(jL22);
        jL22.setBounds(50, 190, 29, 20);

        jL23.setText("a");
        Grafico.add(jL23);
        jL23.setBounds(290, 180, 29, 20);

        jL24.setText("a");
        Grafico.add(jL24);
        jL24.setBounds(30, 230, 29, 20);

        jL25.setText("a");
        Grafico.add(jL25);
        jL25.setBounds(260, 240, 29, 20);

        jL26.setText("a");
        Grafico.add(jL26);
        jL26.setBounds(150, 280, 29, 20);

        jL27.setText("a");
        Grafico.add(jL27);
        jL27.setBounds(250, 170, 29, 20);

        jL28.setText("a");
        Grafico.add(jL28);
        jL28.setBounds(130, 170, 29, 20);

        jL29.setText("a");
        Grafico.add(jL29);
        jL29.setBounds(310, 200, 29, 20);

        jL30.setText("a");
        Grafico.add(jL30);
        jL30.setBounds(180, 280, 29, 20);

        jL31.setText("a");
        Grafico.add(jL31);
        jL31.setBounds(370, 240, 29, 20);

        jL32.setText("a");
        Grafico.add(jL32);
        jL32.setBounds(270, 310, 29, 20);

        jL33.setText("a");
        Grafico.add(jL33);
        jL33.setBounds(180, 120, 29, 20);

        jL34.setText("a");
        Grafico.add(jL34);
        jL34.setBounds(140, 250, 29, 20);

        jL35.setText("a");
        Grafico.add(jL35);
        jL35.setBounds(260, 200, 29, 20);

        jL36.setText("a");
        Grafico.add(jL36);
        jL36.setBounds(130, 300, 29, 20);

        jL37.setText("a");
        Grafico.add(jL37);
        jL37.setBounds(260, 280, 29, 20);

        jL38.setText("a");
        Grafico.add(jL38);
        jL38.setBounds(200, 400, 29, 20);

        std0.setText("S0*");

        std3.setText("S3*");
        std3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std3ActionPerformed(evt);
            }
        });

        std1.setText("S1*");

        std2.setText("S2*");

        std4.setText("S4*");

        std5.setText("S5*");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("F");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("a");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("b");

        jButton1.setText("Dibujar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limp");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(std0, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(std5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(std4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(std3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(std2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(std1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        jLabel11.setText("S1");

        jL2.setText("a");

        jL39.setText("a");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Grafico, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jL1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel11)
                        .addGap(28, 28, 28)
                        .addComponent(jL2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jL39, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jL1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jL2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(jL39, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 171, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void std3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        g2 = (Graphics2D)Grafico.getGraphics();
        g2.setStroke(new BasicStroke(3));
        dibujarFunciones(g2);
        dibujarCaminosS0(g2);
        dibujarCaminosS1(g2);
        dibujarCaminosS2(g2);
        dibujarCaminosS3(g2);
        dibujarCaminosS4(g2);
        dibujarCaminosS5(g2);
        
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Grafico.repaint();
       jL3.setVisible(false);jL4.setVisible(false);jL5.setVisible(false);jL6.setVisible(false);jL7.setVisible(false);jL8.setVisible(false);
        jL9.setVisible(false);jL10.setVisible(false);jL11.setVisible(false);jL12.setVisible(false);jL13.setVisible(false);jL14.setVisible(false);
        jL15.setVisible(false);jL16.setVisible(false);jL17.setVisible(false);jL18.setVisible(false);jL19.setVisible(false);jL19.setVisible(false);
        jL20.setVisible(false);jL21.setVisible(false);jL22.setVisible(false);jL23.setVisible(false);jL24.setVisible(false);jL25.setVisible(false);
        jL26.setVisible(false);jL27.setVisible(false);jL28.setVisible(false);jL28.setVisible(false);jL29.setVisible(false);jL30.setVisible(false);
        jL31.setVisible(false);jL32.setVisible(false);jL33.setVisible(false);jL34.setVisible(false);jL35.setVisible(false);jL36.setVisible(false);
        jL37.setVisible(false);jL38.setVisible(false);jL39.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void dibujarFunciones(Graphics2D g2)
    {
        //DibujaR S0
        if(std0.getText().equalsIgnoreCase("S0"))
        {
            g2.drawOval(180, 50, 60,60 );
            S0.setVisible(true);
        }
        else if(std0.getText().equalsIgnoreCase("S0*"))
        {
            g2.drawOval(185, 55, 50,50 );
            g2.drawOval(180, 50, 60,60 );
            S0.setVisible(true);
        }
        //DibujaR S1
        if(std1.getText().equalsIgnoreCase("S1"))
        {
            S1.setVisible(true);
            g2.drawOval(60, 120, 60,60 );
        }
        else if(std1.getText().equalsIgnoreCase("S1*"))
        {
            S1.setVisible(true);
            g2.drawOval(65, 125, 50,50 );
            g2.drawOval(60, 120, 60,60 );
        }
        //DibujaR S2
        if(std2.getText().equalsIgnoreCase("S2"))
        {
            S2.setVisible(true);
            g2.drawOval(300, 120, 60,60 );
        }
        else if(std2.getText().equalsIgnoreCase("S2*"))
        {
            S2.setVisible(true);
            g2.drawOval(305, 125, 50,50 );
            g2.drawOval(300, 120, 60,60 );
        }
        //DibujaR S3
        if(std3.getText().equalsIgnoreCase("S3"))
        {
            S3.setVisible(true);
            g2.drawOval(60, 240, 60,60 );
        }
        else if(std3.getText().equalsIgnoreCase("S3*"))
        {
            S3.setVisible(true);
            g2.drawOval(65, 245, 50,50 );
            g2.drawOval(60, 240, 60,60 );
        }
        //DibujaR S4
        if(std4.getText().equalsIgnoreCase("S4"))
        {
            S4.setVisible(true);
            g2.drawOval(300, 240, 60,60 );
        }
        else if(std4.getText().equalsIgnoreCase("S4*"))
        {
            S4.setVisible(true);
            g2.drawOval(305, 245, 50,50 );
            g2.drawOval(300, 240, 60,60 );
        }
        //DibujaR S5     
        if(std5.getText().equalsIgnoreCase("S5"))
        {
            S5.setVisible(true);
            g2.drawOval(180, 310, 60,60 );
        }
        else if(std5.getText().equalsIgnoreCase("S5*"))
        {
            S5.setVisible(true);
            g2.drawOval(185, 315, 50,50 );
            g2.drawOval(180, 310, 60,60 );
        }
    }
    public void dibujarCaminosS0(Graphics2D g2)
    {
        //Camino a S0
        if(jtxt1.getText().equalsIgnoreCase("S0") || jtxt2.getText().equalsIgnoreCase("S0"))
        {
            g2.drawLine(200, 50, 200, 20);
            g2.drawLine(200, 20, 220, 20);
            g2.drawLine(220, 20, 220, 50);
            g2.drawLine(195, 45, 205, 45);
            g2.drawLine(195, 45, 200, 50);
            g2.drawLine(205, 45, 200, 50);
            if(jtxt1.getText().equalsIgnoreCase("S0") && jtxt2.getText().equalsIgnoreCase("S0"))
            {
                jL3.setText("a,b");
            }
            else if(jtxt1.getText().equalsIgnoreCase("S0"))
            {
                jL3.setText("a");
            }
            else if(jtxt2.getText().equalsIgnoreCase("S0"))
            {
                jL3.setText("b");
            }
            jL3.setVisible(true);
            
        }
        //Camino a S1
        if(jtxt1.getText().equalsIgnoreCase("S1") || jtxt2.getText().equalsIgnoreCase("S1"))
        {
            g2.drawLine(180, 90, 120, 130);
            g2.drawLine(120,130 , 125, 130);
            g2.drawLine(120,130 , 120, 125);
            if(jtxt1.getText().equalsIgnoreCase("S1") && jtxt2.getText().equalsIgnoreCase("S1"))
            {
                jL4.setText("a,b");
            }
            else if(jtxt1.getText().equalsIgnoreCase("S1"))
            {
                jL4.setText("a");
            }
            else if(jtxt2.getText().equalsIgnoreCase("S1"))
            {
                jL4.setText("b");
            }
            jL4.setVisible(true);
        }
        //Camino a S2
        if(jtxt1.getText().equalsIgnoreCase("S2") || jtxt2.getText().equalsIgnoreCase("S2"))
        {
            g2.drawLine(240, 90, 300, 130);
            g2.drawLine(300,130 , 295, 130);
            g2.drawLine(300,130 , 300, 125);
            if(jtxt1.getText().equalsIgnoreCase("S2") && jtxt2.getText().equalsIgnoreCase("S2"))
            {
                jL5.setText("a,b");
            }
            else if(jtxt1.getText().equalsIgnoreCase("S2"))
            {
                jL5.setText("a");
            }
            else if(jtxt2.getText().equalsIgnoreCase("S2"))
            {
                jL5.setText("b");
            }
            jL5.setVisible(true);
        }
        //CAmino a S3
        if(jtxt1.getText().equalsIgnoreCase("S3") || jtxt2.getText().equalsIgnoreCase("S3"))
        {
            g2.drawLine(190, 110, 105, 240);
            g2.drawLine(105,240 , 110, 240);
            g2.drawLine(105,240 , 103, 235);
            if(jtxt1.getText().equalsIgnoreCase("S3") && jtxt2.getText().equalsIgnoreCase("S3"))
            {
                jL7.setText("a,b");
            }
            else if(jtxt1.getText().equalsIgnoreCase("S3"))
            {
                jL7.setText("a");
            }
            else if(jtxt2.getText().equalsIgnoreCase("S3"))
            {
                jL7.setText("b");
            }
            jL7.setVisible(true);
            
        }
        //Camino a S4
         if(jtxt1.getText().equalsIgnoreCase("S4") || jtxt2.getText().equalsIgnoreCase("S4"))
        {
            g2.drawLine(230, 100, 320, 240);
            g2.drawLine(320,240 , 320, 235);
            g2.drawLine(320,240 , 315, 240);
            if(jtxt1.getText().equalsIgnoreCase("S4") && jtxt2.getText().equalsIgnoreCase("S4"))
            {
                jL6.setText("a,b");
            }
            else if(jtxt1.getText().equalsIgnoreCase("S4"))
            {
                jL6.setText("a");
            }
            else if(jtxt2.getText().equalsIgnoreCase("S4"))
            {
                jL6.setText("b");
            }
            jL6.setVisible(true);
        }
         //Camino a S5
        if(jtxt1.getText().equalsIgnoreCase("S5") || jtxt2.getText().equalsIgnoreCase("S5"))
        {
            g2.drawLine(220, 110, 220, 310);
            g2.drawLine(220,310 , 225, 305);
            g2.drawLine(220,310 , 215, 305);
        }
        if(jtxt1.getText().equalsIgnoreCase("S5") && jtxt2.getText().equalsIgnoreCase("S5"))
        {
            jL8.setText("a,b");
        }
        else if(jtxt1.getText().equalsIgnoreCase("S5"))
        {
            jL8.setText("a");
        }
        else if(jtxt2.getText().equalsIgnoreCase("S5"))
        {
            jL8.setText("b");
        }
        jL8.setVisible(true);
    }
    public void dibujarCaminosS1(Graphics2D g2)
    {
        //Camino a S0
        if(jtxt3.getText().equalsIgnoreCase("S0") || jtxt4.getText().equalsIgnoreCase("S0"))
        {
            g2.drawLine(175, 80, 110, 125);
            g2.drawLine(175, 80, 170, 78);
            g2.drawLine(175, 80, 175, 85);
            
            if(jtxt3.getText().equalsIgnoreCase("S0") && jtxt4.getText().equalsIgnoreCase("S0"))
            {
                jL9.setText("a,b");
            }
            else if(jtxt3.getText().equalsIgnoreCase("S0"))
            {
                jL9.setText("a");
            }
            else if(jtxt4.getText().equalsIgnoreCase("S0"))
            {
                jL9.setText("b");
            }
            jL9.setVisible(true);
            
        }
        //Camino a S1
        if(jtxt3.getText().equalsIgnoreCase("S1") || jtxt4.getText().equalsIgnoreCase("S1"))
        {
            g2.drawLine(60, 140, 30, 140);
            g2.drawLine(30, 140, 30, 160);
            g2.drawLine(30 , 160, 60, 160);
            g2.drawLine(60, 140, 55, 135);
            g2.drawLine(60, 140, 55, 145);
            
            if(jtxt3.getText().equalsIgnoreCase("S1") && jtxt4.getText().equalsIgnoreCase("S1"))
            {
                jL10.setText("a,b");
            }
            else if(jtxt3.getText().equalsIgnoreCase("S1"))
            {
                jL10.setText("a");
            }
            else if(jtxt4.getText().equalsIgnoreCase("S1"))
            {
                jL10.setText("b");
            }
            jL10.setVisible(true);
            
        }
        //Camino a S2
        if(jtxt3.getText().equalsIgnoreCase("S2") || jtxt4.getText().equalsIgnoreCase("S2"))
        {
            g2.drawLine(120, 140, 300, 140);
            g2.drawLine(300, 140, 295, 135);
            g2.drawLine(300, 140, 295, 145);
            
            if(jtxt3.getText().equalsIgnoreCase("S2") && jtxt4.getText().equalsIgnoreCase("S2"))
            {
                jL11.setText("a,b");
            }
            else if(jtxt3.getText().equalsIgnoreCase("S2"))
            {
                jL11.setText("a");
            }
            else if(jtxt4.getText().equalsIgnoreCase("S2"))
            {
                jL11.setText("b");
            }
            jL11.setVisible(true);
            
        }
         //Camino a S3
        if(jtxt3.getText().equalsIgnoreCase("S3") || jtxt4.getText().equalsIgnoreCase("S3"))
        {
            g2.drawLine(100, 180, 100, 240);
            g2.drawLine(100, 240, 95, 235);
            g2.drawLine(100, 240, 105, 235);
            
            if(jtxt3.getText().equalsIgnoreCase("S3") && jtxt4.getText().equalsIgnoreCase("S3"))
            {
                jL12.setText("a,b");
            }
            else if(jtxt3.getText().equalsIgnoreCase("S3"))
            {
                jL12.setText("a");
            }
            else if(jtxt4.getText().equalsIgnoreCase("S3"))
            {
                jL12.setText("b");
            }
            jL12.setVisible(true);
            
        }
         //Camino a S4
        if(jtxt3.getText().equalsIgnoreCase("S4") || jtxt4.getText().equalsIgnoreCase("S4"))
        {
            g2.drawLine(120, 150, 300, 250);
            g2.drawLine(300, 250, 300, 245);
            g2.drawLine(300, 250, 295, 252);
            
            if(jtxt3.getText().equalsIgnoreCase("S4") && jtxt4.getText().equalsIgnoreCase("S4"))
            {
                jL13.setText("a,b");
            }
            else if(jtxt3.getText().equalsIgnoreCase("S4"))
            {
                jL13.setText("a");
            }
            else if(jtxt4.getText().equalsIgnoreCase("S4"))
            {
                jL13.setText("b");
            }
            jL13.setVisible(true);
            
        }
        if(jtxt3.getText().equalsIgnoreCase("S5") || jtxt4.getText().equalsIgnoreCase("S5"))
        {
            g2.drawLine(115, 165, 200, 310);
            g2.drawLine(200, 310, 193, 310);
            g2.drawLine(200, 310, 203, 305);
            
            if(jtxt3.getText().equalsIgnoreCase("S4") && jtxt4.getText().equalsIgnoreCase("S4"))
            {
                jL14.setText("a,b");
            }
            else if(jtxt3.getText().equalsIgnoreCase("S4"))
            {
                jL14.setText("a");
            }
            else if(jtxt4.getText().equalsIgnoreCase("S4"))
            {
                jL14.setText("b");
            }
            jL14.setVisible(true);
            
        }
    }
    public void dibujarCaminosS2(Graphics2D g2)
    {
         //Camino a S0
        if(jtxt5.getText().equalsIgnoreCase("S0") || jtxt6.getText().equalsIgnoreCase("S0"))
        {
            g2.drawLine(240, 100, 300, 140);
            g2.drawLine(240, 100, 245, 100);
            g2.drawLine(240, 100, 240, 105);
            
            if(jtxt5.getText().equalsIgnoreCase("S0") && jtxt6.getText().equalsIgnoreCase("S0"))
            {
                jL15.setText("a,b");
            }
            else if(jtxt5.getText().equalsIgnoreCase("S0"))
            {
                jL15.setText("a");
            }
            else if(jtxt6.getText().equalsIgnoreCase("S0"))
            {
                jL15.setText("b");
            }
            jL15.setVisible(true);
            
        }
        //Camino a S1
        if(jtxt5.getText().equalsIgnoreCase("S1") || jtxt6.getText().equalsIgnoreCase("S1"))
        {
            g2.drawLine(120, 160, 300, 160);
            g2.drawLine(120, 160, 125, 155);
            g2.drawLine(120, 160, 125, 165);
            
            if(jtxt5.getText().equalsIgnoreCase("S1") && jtxt6.getText().equalsIgnoreCase("S1"))
            {
                jL16.setText("a,b");
            }
            else if(jtxt5.getText().equalsIgnoreCase("S1"))
            {
                jL16.setText("a");
            }
            else if(jtxt6.getText().equalsIgnoreCase("S1"))
            {
                jL16.setText("b");
            }
            jL16.setVisible(true);
            
        }
        //Camino a S2
        if(jtxt5.getText().equalsIgnoreCase("S2") || jtxt6.getText().equalsIgnoreCase("S2"))
        {
            g2.drawLine(360, 140, 390, 140);
            g2.drawLine(390, 140, 390, 160);
            g2.drawLine(390, 160, 360, 160);
            g2.drawLine(360, 140, 365, 135);
            g2.drawLine(360, 140, 365, 145);
            
            if(jtxt5.getText().equalsIgnoreCase("S2") && jtxt6.getText().equalsIgnoreCase("S2"))
            {
                jL17.setText("a,b");
            }
            else if(jtxt5.getText().equalsIgnoreCase("S2"))
            {
                jL17.setText("a");
            }
            else if(jtxt6.getText().equalsIgnoreCase("S2"))
            {
                jL17.setText("b");
            }
            jL17.setVisible(true);
            
        }
        //Camino a S3
        if(jtxt5.getText().equalsIgnoreCase("S3") || jtxt6.getText().equalsIgnoreCase("S3"))
        {
            g2.drawLine(300, 160, 120, 250);
            g2.drawLine(120, 250, 120, 245);
            g2.drawLine(120, 250, 125, 252);
            
            if(jtxt5.getText().equalsIgnoreCase("S3") && jtxt6.getText().equalsIgnoreCase("S3"))
            {
                jL18.setText("a,b");
            }
            else if(jtxt5.getText().equalsIgnoreCase("S3"))
            {
                jL18.setText("a");
            }
            else if(jtxt6.getText().equalsIgnoreCase("S3"))
            {
                jL18.setText("b");
            }
            jL18.setVisible(true);
            
        }
        //Camino a S4
        if(jtxt5.getText().equalsIgnoreCase("S4") || jtxt6.getText().equalsIgnoreCase("S4"))
        {
            g2.drawLine(340 , 180, 340, 240);
            g2.drawLine(340, 240, 335, 235);
            g2.drawLine(340, 240, 345, 235);
            
            if(jtxt5.getText().equalsIgnoreCase("S4") && jtxt6.getText().equalsIgnoreCase("S4"))
            {
                jL19.setText("a,b");
            }
            else if(jtxt5.getText().equalsIgnoreCase("S4"))
            {
                jL19.setText("a");
            }
            else if(jtxt6.getText().equalsIgnoreCase("S4"))
            {
                jL19.setText("b");
            }
            jL19.setVisible(true);
            
        }
        
        //Camino a S5
        if(jtxt5.getText().equalsIgnoreCase("S5") || jtxt6.getText().equalsIgnoreCase("S5"))
        {
            g2.drawLine(310, 175, 225, 310);
            
            g2.drawLine(225, 310, 230, 310);
            g2.drawLine(225, 310, 223, 305);
            
            if(jtxt5.getText().equalsIgnoreCase("S5") && jtxt6.getText().equalsIgnoreCase("S5"))
            {
                jL20.setText("a,b");
            }
            else if(jtxt5.getText().equalsIgnoreCase("S5"))
            {
                jL20.setText("a");
            }
            else if(jtxt6.getText().equalsIgnoreCase("S5"))
            {
                jL20.setText("b");
            }
            jL20.setVisible(true);            
        }
        
    }
    public void dibujarCaminosS3(Graphics2D g2)
    {
        //Camino a S0
        if(jtxt7.getText().equalsIgnoreCase("S0") || jtxt8.getText().equalsIgnoreCase("S0"))
        {
            g2.drawLine(115, 245, 200, 115);
            g2.drawLine(200, 115, 195, 115);
            g2.drawLine(200, 115, 201, 120);
            
            if(jtxt7.getText().equalsIgnoreCase("S0") && jtxt8.getText().equalsIgnoreCase("S0"))
            {
                jL21.setText("a,b");
            }
            else if(jtxt7.getText().equalsIgnoreCase("S0"))
            {
                jL21.setText("a");
            }
            else if(jtxt8.getText().equalsIgnoreCase("S0"))
            {
                jL21.setText("b");
            }
            jL21.setVisible(true);            
        }
        //Camino a S1
        if(jtxt7.getText().equalsIgnoreCase("S1") || jtxt8.getText().equalsIgnoreCase("S1"))
        {
            
            g2.drawLine(80, 180, 80, 240);
            g2.drawLine(80, 180, 75, 185);
            g2.drawLine(80, 180, 85, 185);
            
            if(jtxt7.getText().equalsIgnoreCase("S1") && jtxt8.getText().equalsIgnoreCase("S1"))
            {
                jL22.setText("a,b");
            }
            else if(jtxt7.getText().equalsIgnoreCase("S1"))
            {
                jL22.setText("a");
            }
            else if(jtxt8.getText().equalsIgnoreCase("S1"))
            {
                jL22.setText("b");
            }
            jL22.setVisible(true);            
        }
        //Camino a S2
        if(jtxt7.getText().equalsIgnoreCase("S2") || jtxt8.getText().equalsIgnoreCase("S2"))
        {
            
            g2.drawLine(120, 260, 300, 170);
            g2.drawLine(300, 170, 295, 168);
            g2.drawLine(300, 170, 300, 175);
            
            
            if(jtxt7.getText().equalsIgnoreCase("S2") && jtxt8.getText().equalsIgnoreCase("S2"))
            {
                jL23.setText("a,b");
            }
            else if(jtxt7.getText().equalsIgnoreCase("S2"))
            {
                jL23.setText("a");
            }
            else if(jtxt8.getText().equalsIgnoreCase("S2"))
            {
                jL23.setText("b");
            }
            jL23.setVisible(true);            
        }
        //Camino a S3
        if(jtxt7.getText().equalsIgnoreCase("S3") || jtxt8.getText().equalsIgnoreCase("S3"))
        {
            g2.drawLine(30, 260, 60, 260);
            g2.drawLine(30, 260, 30, 280);
            g2.drawLine(30, 280, 60, 280);
            g2.drawLine(55, 255, 60, 260);
            g2.drawLine(55, 265, 60, 260);
            if(jtxt7.getText().equalsIgnoreCase("S3") && jtxt8.getText().equalsIgnoreCase("S3"))
            {
                jL24.setText("a,b");
            }
            else if(jtxt7.getText().equalsIgnoreCase("S3"))
            {
                jL24.setText("a");
            }
            else if(jtxt8.getText().equalsIgnoreCase("S3"))
            {
                jL24.setText("b");
            }
            jL24.setVisible(true);            
        }
        //Camino a S4
        if(jtxt7.getText().equalsIgnoreCase("S4") || jtxt8.getText().equalsIgnoreCase("S4"))
        {
            g2.drawLine(120, 260, 300, 260);
            g2.drawLine(295, 255, 300, 260);
            g2.drawLine(295, 265, 300, 260);
            if(jtxt7.getText().equalsIgnoreCase("S4") && jtxt8.getText().equalsIgnoreCase("S4"))
            {
                jL25.setText("a,b");
            }
            else if(jtxt7.getText().equalsIgnoreCase("S4"))
            {
                jL25.setText("a");
            }
            else if(jtxt8.getText().equalsIgnoreCase("S4"))
            {
                jL25.setText("b");
            }
            jL25.setVisible(true);            
        }
        //Camino a S5
        if(jtxt7.getText().equalsIgnoreCase("S5") || jtxt8.getText().equalsIgnoreCase("S5"))
        {
            g2.drawLine(120, 280, 180, 320);
            g2.drawLine(180, 320, 175, 321);
            g2.drawLine(180, 320, 179, 315);
            if(jtxt7.getText().equalsIgnoreCase("S5") && jtxt8.getText().equalsIgnoreCase("S5"))
            {
                jL26.setText("a,b");
            }
            else if(jtxt7.getText().equalsIgnoreCase("S5"))
            {
                jL26.setText("a");
            }
            else if(jtxt8.getText().equalsIgnoreCase("S5"))
            {
                jL26.setText("b");
            }
            jL26.setVisible(true);            
        }
    }
    public void dibujarCaminosS4(Graphics2D g2)
    {
        if(jtxt9.getText().equalsIgnoreCase("S0") || jtxt10.getText().equalsIgnoreCase("S0"))
        {
            g2.drawLine(220, 110, 310, 250);
            g2.drawLine(220, 110, 225, 110);
            g2.drawLine(220, 110, 218, 115);
            if(jtxt9.getText().equalsIgnoreCase("S0") && jtxt10.getText().equalsIgnoreCase("S0"))
            {
                jL27.setText("a,b");
            }
            else if(jtxt9.getText().equalsIgnoreCase("S0"))
            {
                jL27.setText("a");
            }
            else if(jtxt10.getText().equalsIgnoreCase("S0"))
            {
                jL27.setText("b");
            }
            jL27.setVisible(true);            
        }
        if(jtxt9.getText().equalsIgnoreCase("S1") || jtxt10.getText().equalsIgnoreCase("S1"))
        {
            g2.drawLine(120, 160, 300, 260);          
            g2.drawLine(120, 160, 125, 158);
            g2.drawLine(120, 160, 120, 165);
            if(jtxt9.getText().equalsIgnoreCase("S1") && jtxt10.getText().equalsIgnoreCase("S1"))
            {
                jL28.setText("a,b");
            }
            else if(jtxt9.getText().equalsIgnoreCase("S1"))
            {
                jL28.setText("a");
            }
            else if(jtxt10.getText().equalsIgnoreCase("S1"))
            {
                jL28.setText("b");
            }
            jL28.setVisible(true);            
        }
        if(jtxt9.getText().equalsIgnoreCase("S2") || jtxt10.getText().equalsIgnoreCase("S2"))
        {
            g2.drawLine(320 , 180, 320, 240);          
            g2.drawLine(320, 180, 315, 185);
            g2.drawLine(320, 180, 325, 185);
            if(jtxt9.getText().equalsIgnoreCase("S2") && jtxt10.getText().equalsIgnoreCase("S2"))
            {
                jL29.setText("a,b");
            }
            else if(jtxt9.getText().equalsIgnoreCase("S2"))
            {
                jL29.setText("a");
            }
            else if(jtxt10.getText().equalsIgnoreCase("S2"))
            {
                jL29.setText("b");
            }
            jL29.setVisible(true);            
        }
         if(jtxt9.getText().equalsIgnoreCase("S3") || jtxt10.getText().equalsIgnoreCase("S3"))
        {
            g2.drawLine(120, 280, 300, 280);          
            g2.drawLine(120, 280, 125, 275);
            g2.drawLine(120, 280, 125, 285);
            if(jtxt9.getText().equalsIgnoreCase("S3") && jtxt10.getText().equalsIgnoreCase("S3"))
            {
                jL30.setText("a,b");
            }
            else if(jtxt9.getText().equalsIgnoreCase("S3"))
            {
                jL30.setText("a");
            }
            else if(jtxt10.getText().equalsIgnoreCase("S3"))
            {
                jL30.setText("b");
            }
            jL30.setVisible(true);            
        }
        if(jtxt9.getText().equalsIgnoreCase("S4") || jtxt10.getText().equalsIgnoreCase("S4"))
        {
            g2.drawLine(360, 260, 390, 260);          
            g2.drawLine(390, 260, 390, 280);
            g2.drawLine(390, 280, 360, 280);
            g2.drawLine(360, 260, 365, 255);
            g2.drawLine(360, 260, 365, 265);
            if(jtxt9.getText().equalsIgnoreCase("S4") && jtxt10.getText().equalsIgnoreCase("S4"))
            {
                jL31.setText("a,b");
            }
            else if(jtxt9.getText().equalsIgnoreCase("S4"))
            {
                jL31.setText("a");
            }
            else if(jtxt10.getText().equalsIgnoreCase("S4"))
            {
                jL31.setText("b");
            }
            jL31.setVisible(true);            
        }
        if(jtxt9.getText().equalsIgnoreCase("S5") || jtxt10.getText().equalsIgnoreCase("S5"))
        {
            g2.drawLine(300, 290, 240, 330);          
            g2.drawLine(240, 330, 245, 332);
            g2.drawLine(240, 330, 239, 325);
            
            if(jtxt9.getText().equalsIgnoreCase("S5") && jtxt10.getText().equalsIgnoreCase("S5"))
            {
                jL32.setText("a,b");
            }
            else if(jtxt9.getText().equalsIgnoreCase("S5"))
            {
                jL32.setText("a");
            }
            else if(jtxt10.getText().equalsIgnoreCase("S5"))
            {
                jL32.setText("b");
            }
            jL32.setVisible(true);            
        }
        
    }
    public void dibujarCaminosS5(Graphics2D g2)
    {
        if(jtxt11.getText().equalsIgnoreCase("S0") || jtxt12.getText().equalsIgnoreCase("S0"))
        {
            g2.drawLine(200, 110, 200, 310);          
            g2.drawLine(200, 110, 195, 115);
            g2.drawLine(200, 110, 205, 115);
            
            if(jtxt11.getText().equalsIgnoreCase("S0") && jtxt12.getText().equalsIgnoreCase("S0"))
            {
                jL33.setText("a,b");
            }
            else if(jtxt11.getText().equalsIgnoreCase("S0"))
            {
                jL33.setText("a");
            }
            else if(jtxt12.getText().equalsIgnoreCase("S0"))
            {
                jL33.setText("b");
            }
            jL33.setVisible(true);            
        }
        if(jtxt11.getText().equalsIgnoreCase("S1") || jtxt12.getText().equalsIgnoreCase("S1"))
        {
            g2.drawLine(190, 320,110 , 185);          
            g2.drawLine(110 , 185, 115, 185);
            g2.drawLine(110 , 185, 108, 190);
            
            if(jtxt11.getText().equalsIgnoreCase("S1") && jtxt12.getText().equalsIgnoreCase("S1"))
            {
                jL34.setText("a,b");
            }
            else if(jtxt11.getText().equalsIgnoreCase("S0"))
            {
                jL34.setText("a");
            }
            else if(jtxt12.getText().equalsIgnoreCase("S0"))
            {
                jL34.setText("b");
            }
            jL34.setVisible(true);            
        }
        if(jtxt11.getText().equalsIgnoreCase("S2") || jtxt12.getText().equalsIgnoreCase("S2"))
        {
           g2.drawLine(300, 165, 210, 310);            
            g2.drawLine(300, 165, 300, 170);
            g2.drawLine(300, 165, 297, 165);
            
            if(jtxt11.getText().equalsIgnoreCase("S2") && jtxt12.getText().equalsIgnoreCase("S2"))
            {
                jL35.setText("a,b");
            }
            else if(jtxt11.getText().equalsIgnoreCase("S2"))
            {
                jL35.setText("a");
            }
            else if(jtxt12.getText().equalsIgnoreCase("S2"))
            {
                jL35.setText("b");
            }
            jL35.setVisible(true);            
        }
        if(jtxt11.getText().equalsIgnoreCase("S3") || jtxt12.getText().equalsIgnoreCase("S3"))
        {
            g2.drawLine(120, 290, 180, 330);            
            g2.drawLine(120, 290, 125, 288);
            g2.drawLine(120, 290, 120, 295);
            
            if(jtxt11.getText().equalsIgnoreCase("S3") && jtxt12.getText().equalsIgnoreCase("S3"))
            {
                jL36.setText("a,b");
            }
            else if(jtxt11.getText().equalsIgnoreCase("S3"))
            {
                jL36.setText("a");
            }
            else if(jtxt12.getText().equalsIgnoreCase("S3"))
            {
                jL36.setText("b");
            }
            jL36.setVisible(true);            
        }
        if(jtxt11.getText().equalsIgnoreCase("S4") || jtxt12.getText().equalsIgnoreCase("S4"))
        {
            g2.drawLine(300, 280, 240, 320);            
            g2.drawLine(300, 280, 300, 285);
            g2.drawLine(300, 280, 295, 278);
            
            if(jtxt11.getText().equalsIgnoreCase("S4") && jtxt12.getText().equalsIgnoreCase("S4"))
            {
                jL37.setText("a,b");
            }
            else if(jtxt11.getText().equalsIgnoreCase("S4"))
            {
                jL37.setText("a");
            }
            else if(jtxt12.getText().equalsIgnoreCase("S4"))
            {
                jL37.setText("b");
            }
            jL37.setVisible(true);            
        }
        if(jtxt11.getText().equalsIgnoreCase("S5") || jtxt12.getText().equalsIgnoreCase("S5"))
        {
            g2.drawLine(200, 370, 200, 400);            
            g2.drawLine(200, 400, 220, 400);
            g2.drawLine(220, 400, 220, 370);
            g2.drawLine(215, 375, 220, 370);
            g2.drawLine(225, 375, 220, 370);
            
            
            if(jtxt11.getText().equalsIgnoreCase("S5") && jtxt12.getText().equalsIgnoreCase("S5"))
            {
                jL38.setText("a,b");
            }
            else if(jtxt11.getText().equalsIgnoreCase("S5"))
            {
                jL38.setText("a");
            }
            else if(jtxt12.getText().equalsIgnoreCase("S5"))
            {
                jL38.setText("b");
            }
            jL38.setVisible(true);            
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Grafos2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Grafico;
    private javax.swing.JLabel S0;
    private javax.swing.JLabel S1;
    private javax.swing.JLabel S2;
    private javax.swing.JLabel S3;
    private javax.swing.JLabel S4;
    private javax.swing.JLabel S5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL10;
    private javax.swing.JLabel jL11;
    private javax.swing.JLabel jL12;
    private javax.swing.JLabel jL13;
    private javax.swing.JLabel jL14;
    private javax.swing.JLabel jL15;
    private javax.swing.JLabel jL16;
    private javax.swing.JLabel jL17;
    private javax.swing.JLabel jL18;
    private javax.swing.JLabel jL19;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL20;
    private javax.swing.JLabel jL21;
    private javax.swing.JLabel jL22;
    private javax.swing.JLabel jL23;
    private javax.swing.JLabel jL24;
    private javax.swing.JLabel jL25;
    private javax.swing.JLabel jL26;
    private javax.swing.JLabel jL27;
    private javax.swing.JLabel jL28;
    private javax.swing.JLabel jL29;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL30;
    private javax.swing.JLabel jL31;
    private javax.swing.JLabel jL32;
    private javax.swing.JLabel jL33;
    private javax.swing.JLabel jL34;
    private javax.swing.JLabel jL35;
    private javax.swing.JLabel jL36;
    private javax.swing.JLabel jL37;
    private javax.swing.JLabel jL38;
    private javax.swing.JLabel jL39;
    private javax.swing.JLabel jL4;
    private javax.swing.JLabel jL5;
    private javax.swing.JLabel jL6;
    private javax.swing.JLabel jL7;
    private javax.swing.JLabel jL8;
    private javax.swing.JLabel jL9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jtxt1;
    private javax.swing.JTextField jtxt10;
    private javax.swing.JTextField jtxt11;
    private javax.swing.JTextField jtxt12;
    private javax.swing.JTextField jtxt2;
    private javax.swing.JTextField jtxt3;
    private javax.swing.JTextField jtxt4;
    private javax.swing.JTextField jtxt5;
    private javax.swing.JTextField jtxt6;
    private javax.swing.JTextField jtxt7;
    private javax.swing.JTextField jtxt8;
    private javax.swing.JTextField jtxt9;
    private javax.swing.JTextField std0;
    private javax.swing.JTextField std1;
    private javax.swing.JTextField std2;
    private javax.swing.JTextField std3;
    private javax.swing.JTextField std4;
    private javax.swing.JTextField std5;
    // End of variables declaration//GEN-END:variables
}
