/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automastasmario;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javafx.scene.shape.QuadCurve;

/**
 *
 * @author Jahir
 */
public class AutomataGraphics extends javax.swing.JFrame {

    /**
     * Creates new form AutomataGraphics
     */
    public AutomataGraphics() {
        initComponents();
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        S2.setVisible(false);
        S3.setVisible(false);
        S0.setVisible(false);
        S1.setVisible(false);
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grafico = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        S0 = new javax.swing.JLabel();
        S1 = new javax.swing.JLabel();
        S2 = new javax.swing.JLabel();
        S3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        std1 = new javax.swing.JTextField();
        Funcion = new javax.swing.JLabel();
        AA = new javax.swing.JLabel();
        jtxt1 = new javax.swing.JTextField();
        jtxt2 = new javax.swing.JTextField();
        std2 = new javax.swing.JTextField();
        jtxt3 = new javax.swing.JTextField();
        jtxt4 = new javax.swing.JTextField();
        jtxt6 = new javax.swing.JTextField();
        std3 = new javax.swing.JTextField();
        jtxt5 = new javax.swing.JTextField();
        BB = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtxt7 = new javax.swing.JTextField();
        jtxt8 = new javax.swing.JTextField();
        std4 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grafico.setBackground(new java.awt.Color(255, 255, 255));
        grafico.setPreferredSize(new java.awt.Dimension(400, 400));
        grafico.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel3.setText("a");
        jLabel3.setEnabled(false);
        grafico.add(jLabel3);
        jLabel3.setBounds(180, 67, 30, 20);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel4.setText("a");
        jLabel4.setEnabled(false);
        grafico.add(jLabel4);
        jLabel4.setBounds(160, 110, 30, 20);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel5.setText("a");
        jLabel5.setEnabled(false);
        grafico.add(jLabel5);
        jLabel5.setBounds(250, 3, 40, 20);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel6.setText("a");
        jLabel6.setEnabled(false);
        grafico.add(jLabel6);
        jLabel6.setBounds(250, 320, 30, 20);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel7.setText("a");
        jLabel7.setEnabled(false);
        grafico.add(jLabel7);
        jLabel7.setBounds(160, 260, 30, 21);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel8.setText("a");
        jLabel8.setEnabled(false);
        grafico.add(jLabel8);
        jLabel8.setBounds(180, 213, 30, 20);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel9.setText("a");
        jLabel9.setEnabled(false);
        grafico.add(jLabel9);
        jLabel9.setBounds(220, 183, 30, 20);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel10.setText("a");
        jLabel10.setEnabled(false);
        grafico.add(jLabel10);
        jLabel10.setBounds(225, 132, 30, 20);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel13.setText("a");
        jLabel13.setEnabled(false);
        grafico.add(jLabel13);
        jLabel13.setBounds(60, 132, 30, 20);

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel16.setText("a");
        jLabel16.setEnabled(false);
        grafico.add(jLabel16);
        jLabel16.setBounds(122, 163, 30, 20);

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel17.setText("a");
        jLabel17.setEnabled(false);
        grafico.add(jLabel17);
        jLabel17.setBounds(100, 3, 40, 20);

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel18.setText("a");
        jLabel18.setEnabled(false);
        grafico.add(jLabel18);
        jLabel18.setBounds(99, 320, 30, 20);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel11.setText("a");
        jLabel11.setEnabled(false);
        grafico.add(jLabel11);
        jLabel11.setBounds(149, 181, 30, 20);

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel15.setText("a");
        jLabel15.setEnabled(false);
        grafico.add(jLabel15);
        jLabel15.setBounds(229, 160, 30, 20);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel14.setText("a");
        jLabel14.setEnabled(false);
        grafico.add(jLabel14);
        jLabel14.setBounds(280, 160, 40, 20);

        S0.setText("S0");
        grafico.add(S0);
        S0.setBounds(100, 90, 20, 14);

        S1.setText("S1");
        grafico.add(S1);
        S1.setBounds(260, 90, 20, 14);

        S2.setText("S2");
        grafico.add(S2);
        S2.setBounds(100, 240, 20, 14);

        S3.setText("S3");
        grafico.add(S3);
        S3.setBounds(260, 240, 20, 14);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel12.setText("a");
        jLabel12.setEnabled(false);
        grafico.add(jLabel12);
        jLabel12.setBounds(130, 140, 38, 21);

        std1.setText("S0*");
        std1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std1ActionPerformed(evt);
            }
        });

        Funcion.setText("F");

        AA.setText("a");

        jtxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt1ActionPerformed(evt);
            }
        });

        jtxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt2ActionPerformed(evt);
            }
        });

        std2.setText("S1");
        std2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std2ActionPerformed(evt);
            }
        });

        jtxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt3ActionPerformed(evt);
            }
        });

        jtxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt4ActionPerformed(evt);
            }
        });

        jtxt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt6ActionPerformed(evt);
            }
        });

        std3.setText("S2");
        std3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std3ActionPerformed(evt);
            }
        });

        jtxt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt5ActionPerformed(evt);
            }
        });

        BB.setText("b");

        jButton1.setText("Dibujar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtxt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt7ActionPerformed(evt);
            }
        });

        jtxt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt8ActionPerformed(evt);
            }
        });

        std4.setText("S3");
        std4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std4ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel29.setText("a");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(std2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(std3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(std1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Funcion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AA))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(std4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(506, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(113, 113, 113)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Funcion)
                    .addComponent(AA)
                    .addComponent(BB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(std1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(std2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(std3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(std4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(144, 144, 144)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(312, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(103, 103, 103)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void std1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std1ActionPerformed

    private void jtxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt1ActionPerformed

    private void jtxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt2ActionPerformed

    private void std2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std2ActionPerformed

    private void jtxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt3ActionPerformed

    private void jtxt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt4ActionPerformed

    private void jtxt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt6ActionPerformed

    private void std3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std3ActionPerformed

    private void jtxt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       Graphics g = grafico.getGraphics();
       Graphics2D g2 =(Graphics2D)g;
       g2.setStroke(new BasicStroke(3));
       Funciones(g2);
       CaminosS0(g2);
       CaminosS1(g2);
       CaminosS2(g2);
       CaminosS3(g2);      
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt7ActionPerformed

    private void jtxt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt8ActionPerformed

    private void std4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Funciones(Graphics2D g2)
    {
        
        if(std1.getText().equals("S0*") )
       {
           S0.setVisible(true);
           g2.setColor(Color.red);
           g2.drawOval(85, 75, 50, 50);
           g2.drawOval(80, 70, 60, 60);
           
       }
       else if(std1.getText().equals("S0"))
       {   
           S0.setVisible(true);
           g2.setColor(Color.red);
           g2.drawOval(80, 70, 60, 60);
           
       }
       g2.setColor(Color.black);
       if(std2.getText().equals("S1*") )
       {   
           S1.setVisible(true);
           g2.drawOval(235, 75, 50, 50);
           g2.drawOval(230, 70, 60, 60);
           
       }
       else if(std2.getText().equals("S1"))
       {   
           S1.setVisible(true);           
           g2.drawOval(230, 70, 60, 60);
           
       }
       if(std3.getText().equals("S2*") )
       {   
           S2.setVisible(true);
           g2.drawOval(85, 220, 50, 50);
           g2.drawOval(80, 215, 60, 60);
           
       }
       else if(std3.getText().equals("S2"))
       {
           S2.setVisible(true);
           g2.drawOval(80, 215, 60, 60);
           
       }
       if(std4.getText().equals("S3*") )
       {   
           S3.setVisible(true);
           g2.drawOval(235, 220, 50, 50);
           g2.drawOval(230, 215, 60, 60);
           
       }
       else if(std4.getText().equals("S3"))
       {
           S3.setVisible(true);
           g2.drawOval(230, 215, 60, 60);   
       }
       
       
        
    }
    public void CaminosS0(Graphics2D g2)
    {
       if(jtxt1.getText().equals("S0") || jtxt2.getText().equals("S0"))
       {
           g2.drawLine(125,70, 125, 30);
           g2.drawLine(125,30, 100, 30);
           g2.drawLine(100,30, 100, 70);
           g2.drawLine(95,65, 105, 65);
           g2.drawLine(95,65, 100, 70);
           g2.drawLine(105,65, 100, 70);
           if(jtxt1.getText().equals("S0") && jtxt2.getText().equals("S0"))
           {
               jLabel17.setText("a,b");
           }
           else if(jtxt1.getText().equals("S0"))
           {
               jLabel17.setText("a");
           }
           else if(jtxt2.getText().equals("S0"))
           {
               jLabel17.setText("b");
           }
           jLabel17.setVisible(true);
       }
       if(jtxt1.getText().equals("S1") || jtxt2.getText().equals("S1"))
       {
           g2.drawLine(140, 90, 225, 90);
           g2.drawLine(220, 85, 220, 95);
           g2.drawLine(220, 85, 225, 90);
           g2.drawLine(220, 95, 225, 90);
           if(jtxt1.getText().equals("S1") && jtxt2.getText().equals("S1"))
           {
               jLabel3.setText("a,b");
           }
           else if(jtxt1.getText().equals("S1"))
           {
               jLabel3.setText("a");
           }
           else if(jtxt2.getText().equals("S1"))
           {
               jLabel3.setText("b");
           }
           jLabel3.setVisible(true);
           
       }
       if(jtxt1.getText().equals("S2") || jtxt2.getText().equals("S2"))
       {
           g2.drawLine(120, 135, 120, 210);
           g2.drawLine(115, 205, 125, 205);
           g2.drawLine(115, 205, 120, 210);
           g2.drawLine(125, 205, 120, 210);
            if(jtxt1.getText().equals("S2") && jtxt2.getText().equals("S2"))
           {
               jLabel16.setText("a,b");
           }
           else if(jtxt1.getText().equals("S2"))
           {
               jLabel16.setText("a");
           }
           else if(jtxt2.getText().equals("S2"))
           {
               jLabel16.setText("b");
           }
           jLabel16.setVisible(true);
           
       }
       if(jtxt1.getText().equals("S3") || jtxt2.getText().equals("S3"))
       {
           g2.drawLine(135,120,240,220);
           g2.drawLine(240, 220, 230, 220);
           g2.drawLine(240, 220, 240, 210);
           g2.drawLine(230, 220, 240, 210);
           if(jtxt1.getText().equals("S3") && jtxt2.getText().equals("S3"))
           {
               jLabel9.setText("a,b");
           }
           else if(jtxt1.getText().equals("S3"))
           {
               jLabel9.setText("a");
           }
           else if(jtxt2.getText().equals("S3"))
           {
               jLabel9.setText("b");
           }
           jLabel9.setVisible(true);        
       }
           
        
    }
    public void CaminosS1(Graphics2D g2)
    {
        if(jtxt3.getText().equals("S0") || jtxt4.getText().equals("S0"))
        {
           g2.drawLine(145, 110, 230, 110);
           g2.drawLine(150, 105, 150, 115);
           g2.drawLine(150, 105, 145, 110);
           g2.drawLine(150, 115, 145, 110);
           if(jtxt3.getText().equals("S0") && jtxt4.getText().equals("S0"))
           {
               jLabel4.setText("a,b");
           }
           else if(jtxt3.getText().equals("S0"))
           {
               jLabel4.setText("a");
           }
           else if(jtxt4.getText().equals("S0"))
           {
               jLabel4.setText("b");
           }
           jLabel4.setVisible(true);
           
        }
        if(jtxt3.getText().equals("S1") || jtxt4.getText().equals("S1"))
        {
           g2.drawLine(275,70, 275, 30);
           g2.drawLine(275,30, 250, 30);
           g2.drawLine(250,30, 250, 70);
           g2.drawLine(245,65, 255, 65);
           g2.drawLine(245,65, 250, 70);
           g2.drawLine(255,65, 250, 70);
           if(jtxt3.getText().equals("S1") && jtxt4.getText().equals("S1"))
           {
               jLabel5.setText("a,b");
           }
           else if(jtxt3.getText().equals("S1"))
           {
               jLabel5.setText("a");
           }
           else if(jtxt4.getText().equals("S1"))
           {
               jLabel5.setText("b");
           }
           jLabel5.setVisible(true);
           
           
        }
        if(jtxt3.getText().equals("S2") || jtxt4.getText().equals("S2"))
        {
            g2.drawLine(135,220,235,115);
            g2.drawLine(135,220,135,210);
            g2.drawLine(135,220,145,220);
            g2.drawLine(135,210,145,220);
            if(jtxt3.getText().equals("S2") && jtxt4.getText().equals("S2"))
           {
               jLabel11.setText("a,b");
           }
           else if(jtxt3.getText().equals("S2"))
           {
               jLabel11.setText("a");
           }
           else if(jtxt4.getText().equals("S2"))
           {
               jLabel11.setText("b");
           }
           jLabel11.setVisible(true);
           
        }
        if(jtxt3.getText().equals("S3") || jtxt4.getText().equals("S3"))
       {
           g2.drawLine(270, 135, 270, 210);
           g2.drawLine(265, 205, 275, 205);
           g2.drawLine(265, 205, 270, 210);
           g2.drawLine(275, 205, 270, 210);         
           if(jtxt3.getText().equals("S3") && jtxt4.getText().equals("S3"))
           {
               jLabel14.setText("a,b");
           }
           else if(jtxt3.getText().equals("S3"))
           {
               jLabel14.setText("a");
           }
           else if(jtxt4.getText().equals("S3"))
           {
               jLabel14.setText("b");
           }
           jLabel14.setVisible(true);
       }
    }
    public void CaminosS2(Graphics2D g2)
    {
        if(jtxt5.getText().equals("S0") || jtxt6.getText().equals("S0"))
        {
           g2.drawLine(100, 135, 100, 210);
           g2.drawLine(95, 140, 105, 140);
           g2.drawLine(95, 140, 100, 135);
           g2.drawLine(100, 135, 105, 140);
           if(jtxt5.getText().equals("S0") && jtxt6.getText().equals("S0"))
           {
               jLabel13.setText("a,b");
           }
           else if(jtxt5.getText().equals("S0"))
           {
               jLabel13.setText("a");
           }
           else if(jtxt6.getText().equals("S0"))
           {
               jLabel13.setText("b");
           }
           jLabel13.setVisible(true);
        }
        if(jtxt5.getText().equals("S1") || jtxt6.getText().equals("S1"))
        {
           g2.drawLine(140,235,245,125);
           g2.drawLine(245,125,235,125);
           g2.drawLine(245,125,245,135);
           g2.drawLine(235,125,245,135);
           if(jtxt5.getText().equals("S1") && jtxt6.getText().equals("S1"))
           {
               jLabel10.setText("a,b");
           }
           else if(jtxt5.getText().equals("S1"))
           {
               jLabel10.setText("a");
           }
           else if(jtxt6.getText().equals("S1"))
           {
               jLabel10.setText("b");
           }
           jLabel10.setVisible(true);
        }
        if(jtxt5.getText().equals("S2") || jtxt6.getText().equals("S2"))
        {
           g2.drawLine(125,275, 125, 315);
           g2.drawLine(125,315, 100, 315);
           g2.drawLine(100,315, 100, 275);
           g2.drawLine(95,280, 105, 280);
           g2.drawLine(95,280, 100, 275);
           g2.drawLine(105,280, 100, 275);
           if(jtxt5.getText().equals("S2") && jtxt6.getText().equals("S2"))
           {
               jLabel18.setText("a,b");
           }
           else if(jtxt5.getText().equals("S2"))
           {
               jLabel18.setText("a");
           }
           else if(jtxt6.getText().equals("S2"))
           {
               jLabel18.setText("b");
           }
           jLabel18.setVisible(true);
        }
        if(jtxt5.getText().equals("S3") || jtxt6.getText().equals("S3"))
       {
           g2.drawLine(140, 235, 225, 235);
           g2.drawLine(220, 230, 220, 240);
           g2.drawLine(220, 230, 225, 235);
           g2.drawLine(220, 240, 225, 235);
           if(jtxt5.getText().equals("S3") && jtxt6.getText().equals("S3"))
           {
               jLabel8.setText("a,b");
           }
           else if(jtxt5.getText().equals("S3"))
           {
               jLabel8.setText("a");
           }
           else if(jtxt6.getText().equals("S3"))
           {
               jLabel8.setText("b");
           }
           jLabel8.setVisible(true);
       }
    }
    public void CaminosS3(Graphics2D g2)
    {
        if(jtxt7.getText().equals("S0") || jtxt8.getText().equals("S0"))
        {
           g2.drawLine(125,130,230,230);
           g2.drawLine(125,130,125,140);
           g2.drawLine(125,130,135,130);
           g2.drawLine(125,140,135,130);
           if(jtxt7.getText().equals("S0") && jtxt8.getText().equals("S0"))
           {
               jLabel12.setText("a,b");
           }
           else if(jtxt7.getText().equals("S0"))
           {
               jLabel12.setText("a");
           }
           else if(jtxt8.getText().equals("S0"))
           {
               jLabel12.setText("b");
           }
           jLabel12.setVisible(true);
        }
        if(jtxt7.getText().equals("S1") || jtxt8.getText().equals("S1"))
        {
           g2.drawLine(250, 135, 250, 210);
           g2.drawLine(245, 140, 255, 140);
           g2.drawLine(245, 140, 250, 135);
           g2.drawLine(255, 140, 250, 135);
           if(jtxt7.getText().equals("S1") && jtxt8.getText().equals("S1"))
           {
               jLabel15.setText("a,b");
           }
           else if(jtxt7.getText().equals("S1"))
           {
               jLabel15.setText("a");
           }
           else if(jtxt8.getText().equals("S1"))
           {
               jLabel15.setText("b");
           }
           jLabel15.setVisible(true);
           
        }
        if(jtxt7.getText().equals("S2") || jtxt8.getText().equals("S2"))
        {
           g2.drawLine(140, 255, 225, 255);
           g2.drawLine(145, 250, 145, 260);
           g2.drawLine(145, 250, 140, 255);
           g2.drawLine(145, 260, 140, 255);
           if(jtxt7.getText().equals("S2") && jtxt8.getText().equals("S2"))
           {
               jLabel7.setText("a,b");
           }
           else if(jtxt7.getText().equals("S2"))
           {
               jLabel7.setText("a");
           }
           else if(jtxt8.getText().equals("S2"))
           {
               jLabel7.setText("b");
           }
           jLabel7.setVisible(true);
        }
        if(jtxt7.getText().equals("S3") || jtxt8.getText().equals("S3"))
       {
           g2.drawLine(275,275, 275, 315);
           g2.drawLine(275,315, 250, 315);
           g2.drawLine(250,315, 250, 275);
           g2.drawLine(245,280, 255, 280);
           g2.drawLine(245,280, 250, 275);
           g2.drawLine(255,280, 250, 275);
           if(jtxt7.getText().equals("S3") && jtxt8.getText().equals("S3"))
           {
               jLabel6.setText("a,b");
           }
           else if(jtxt7.getText().equals("S3"))
           {
               jLabel6.setText("a");
           }
           else if(jtxt8.getText().equals("S3"))
           {
               jLabel6.setText("b");
           }
           jLabel6.setVisible(true);
       }
        
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutomataGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutomataGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutomataGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutomataGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AutomataGraphics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AA;
    private javax.swing.JLabel BB;
    private javax.swing.JLabel Funcion;
    private javax.swing.JLabel S0;
    private javax.swing.JLabel S1;
    private javax.swing.JLabel S2;
    private javax.swing.JLabel S3;
    private javax.swing.JPanel grafico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtxt1;
    private javax.swing.JTextField jtxt2;
    private javax.swing.JTextField jtxt3;
    private javax.swing.JTextField jtxt4;
    private javax.swing.JTextField jtxt5;
    private javax.swing.JTextField jtxt6;
    private javax.swing.JTextField jtxt7;
    private javax.swing.JTextField jtxt8;
    private javax.swing.JTextField std1;
    private javax.swing.JTextField std2;
    private javax.swing.JTextField std3;
    private javax.swing.JTextField std4;
    // End of variables declaration//GEN-END:variables
}
