/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RadioButton;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author pnc_h
 */
public class ejemploRadioButton extends javax.swing.JFrame {

    /**
     * Creates new form ejemploRadioButton
     */
    public ejemploRadioButton() {
        initComponents();
        this.getContentPane().setBackground(Color.black);
        rb1.add(rojo);
        rb1.add(azul);
        rb1.add(verde);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb1 = new javax.swing.ButtonGroup();
        azul = new javax.swing.JRadioButton();
        verde = new javax.swing.JRadioButton();
        rojo = new javax.swing.JRadioButton();
        saludo = new javax.swing.JRadioButton();
        logo = new javax.swing.JRadioButton();
        mario = new javax.swing.JRadioButton();
        txt1 = new javax.swing.JTextField();
        jl1 = new javax.swing.JLabel();
        jl3 = new javax.swing.JLabel();
        jl2 = new javax.swing.JLabel();
        jl4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        azul.setBackground(new java.awt.Color(0, 0, 0));
        azul.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        azul.setForeground(new java.awt.Color(0, 0, 255));
        azul.setText("Azul");
        azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulActionPerformed(evt);
            }
        });

        verde.setBackground(new java.awt.Color(0, 0, 0));
        verde.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        verde.setForeground(new java.awt.Color(0, 204, 102));
        verde.setText("Verde");
        verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdeActionPerformed(evt);
            }
        });

        rojo.setBackground(new java.awt.Color(0, 0, 0));
        rojo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rojo.setForeground(new java.awt.Color(255, 0, 51));
        rojo.setText("Rojo");
        rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojoActionPerformed(evt);
            }
        });

        saludo.setBackground(new java.awt.Color(0, 0, 0));
        saludo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saludo.setForeground(new java.awt.Color(255, 255, 255));
        saludo.setText("Saludo");
        saludo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saludoActionPerformed(evt);
            }
        });

        logo.setBackground(new java.awt.Color(0, 0, 0));
        logo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setText("Logo");
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });

        mario.setBackground(new java.awt.Color(0, 0, 0));
        mario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mario.setForeground(new java.awt.Color(255, 255, 255));
        mario.setText("Mario");
        mario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marioActionPerformed(evt);
            }
        });

        txt1.setEditable(false);

        jl1.setBackground(new java.awt.Color(51, 51, 51));
        jl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl1.setForeground(new java.awt.Color(255, 255, 255));

        jl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl3.setForeground(new java.awt.Color(255, 255, 255));

        jl2.setBackground(new java.awt.Color(0, 0, 0));
        jl2.setForeground(new java.awt.Color(255, 255, 255));

        jl4.setEditable(false);
        jl4.setBackground(new java.awt.Color(0, 0, 0));
        jl4.setFont(new java.awt.Font("ITC Zapf Chancery", 3, 24)); // NOI18N
        jl4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jl4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rojo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(azul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(verde, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(saludo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(mario, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(rojo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(azul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verde))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mario)
                        .addComponent(saludo))
                    .addComponent(logo))
                .addGap(19, 19, 19)
                .addComponent(jl1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jl4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojoActionPerformed
        
            txt1.setBackground(Color.red);
        
    }//GEN-LAST:event_rojoActionPerformed

    private void azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azulActionPerformed
        txt1.setBackground(Color.BLUE);
    }//GEN-LAST:event_azulActionPerformed

    private void verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdeActionPerformed
         
        txt1.setBackground(Color.GREEN);
    }//GEN-LAST:event_verdeActionPerformed

    private void marioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marioActionPerformed
        if(mario.isSelected()==true)
        {
            jl1.setText("Mario no dejo que presentara el programa original...");
        }
        else{
            jl1.setText("");
        }
    }//GEN-LAST:event_marioActionPerformed

    private void saludoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saludoActionPerformed
        if(saludo.isSelected()==true){
            jl3.setText("Hola");
        }
        else{
            jl3.setText("");
        }
    }//GEN-LAST:event_saludoActionPerformed

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        if(logo.isSelected()==true)
        {
            jl2.setIcon(new ImageIcon("C:/Users/Jahir/Documents/NetBeansProjects/Expo/Expo/Imagenes/horda.png"));
            jl4.setText("La Horda....Con H");
        }
        else{
            jl2.setIcon(null);
            jl4.setText("");
        }
    }//GEN-LAST:event_logoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejemploRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejemploRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejemploRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejemploRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejemploRadioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton azul;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl2;
    private javax.swing.JLabel jl3;
    private javax.swing.JTextField jl4;
    private javax.swing.JRadioButton logo;
    private javax.swing.JRadioButton mario;
    private javax.swing.ButtonGroup rb1;
    private javax.swing.JRadioButton rojo;
    private javax.swing.JRadioButton saludo;
    private javax.swing.JTextField txt1;
    private javax.swing.JRadioButton verde;
    // End of variables declaration//GEN-END:variables
}
